### ISSUE TITLE
Deleting song shifts shortcuts to the left 

### ISSUE THREAD

**Issue by starshooter64** [devolution2409/Lidl-Soundboard#1]
If you set a couple of songs and their shortcuts, deleting the first song will shift the shortcut of the 2nd song to the shortcut of the deleted one. 

i.e : 

song 1 : shortcut 1 
song 2 : shortcut 2 

delete song 1 and it becomes : 

song 2 : shortcut 1 

DansW

**Comment by devolution2409** [comment]
Fixed in release 0.42 👏 🌞
