### ISSUE TITLE
Importing EXP soundboard JSON file dialog doesn't show JSON files by default.

### ISSUE THREAD

**Issue by wakeuphate** [devolution2409/Lidl-Soundboard#3]
The file type is set to .json but .json files do not show up when you're in the folder unless you type something like `*.json` in the file name box:

As you open it:
![image](https://user-images.githubusercontent.com/377813/39967947-9cab2126-56bc-11e8-8699-ddd03c3e73bc.png)

After typing `*.json` and hitting return:
![image](https://user-images.githubusercontent.com/377813/39967952-b3b1a926-56bc-11e8-802b-3b6d09a10541.png)

**Comment by devolution2409** [comment]
Fixed
