### ISSUE TITLE
Loop playsounds

### ISSUE THREAD

**Issue by LiveLaden** [devolution2409/Lidl-Soundboard#6]
An option to loop playsounds when they are over

**Comment by devolution2409** [comment]
- add an option in the enum for the singleton loop playback [here ](https://github.com/devolution2409/Lidl-Soundboard/blob/master/include/EnumsAndStructs.h)

- add the option in the GUI to be able to use it when adding/editing a sound
- add the relevant play and timer option [here](https://github.com/devolution2409/Lidl-Soundboard/blob/master/CustomPlayer.cpp) (inspiring from sequential auto)

- VI VON ZULUL

**Comment by devolution2409** [comment]
Implemented in [3231b49](https://github.com/devolution2409/Lidl-Soundboard/commit/3231b49d9d2b440777e0767cf70e8a2c798f88c8)
